# Generated by Django 4.1.3 on 2022-11-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sented_emails',
            new_name='SentedEmails',
        ),
    ]
